model_params:
  num_classes: {{ num_classes }}

args:
  expdir: {{ expdir }}

stages:

  state_params:
    main_metric: &reduce_metric iou_hard
    minimize_metric: False

  data_params:
    num_workers: {{ num_workers }}
    batch_size: {{ batch_size }}
    per_gpu_scaling: True
    image_size: {{ image_size }}
    in_csv_train: {{ dataset_path }}/dataset_train.csv
    in_csv_valid: {{ dataset_path }}/dataset_valid.csv
    datapath: {{ dataset_path }}

  criterion_params:
    _key_value: True

    bce:
      criterion: BCEWithLogitsLoss
    dice:
      criterion: DiceLoss
    iou:
      criterion: IoULoss

  callbacks_params:
    loss_bce:
      callback: CriterionCallback
      input_key: mask
      output_key: logits
      prefix: loss_bce
      criterion_key: bce
      multiplier: 1.0
    loss_dice:
      callback: CriterionCallback
      input_key: mask
      output_key: logits
      prefix: loss_dice
      criterion_key: dice
      multiplier: 1.0
    loss_iou:
      callback: CriterionCallback
      input_key: mask
      output_key: logits
      prefix: loss_iou
      criterion_key: iou
      multiplier: 1.0

    loss_aggregator:
      callback: CriterionAggregatorCallback
      prefix: &aggregated_loss loss
      loss_aggregate_fn: "mean" # or "sum"
      multiplier: 1.0 # scale factor for the aggregated loss

    iou_soft:
      callback: IouCallback
      input_key: mask
      output_key: logits
      prefix: iou_soft
    iou_hard:
      callback: IouCallback
      input_key: mask
      output_key: logits
      prefix: iou_hard
      threshold: 0.5

    optimizer:
      callback: OptimizerCallback
      loss_key: *aggregated_loss
    scheduler:
      callback: SchedulerCallback
      reduce_metric: *reduce_metric
    saver:
      callback: CheckpointCallback

  # infer:
  #
  #   data_params:
  #     num_workers: {{ num_workers }}
  #     batch_size: {{ batch_size }}
  #     per_gpu_scaling: True
  #     in_csv: null
  #     in_csv_train: null
  #     in_csv_valid: {{ dataset_path }}/dataset_valid.csv
  #     in_csv_infer: {{ dataset_path }}/dataset_train.csv
  #     datapath: {{ dataset_path }}
  #
  #   callbacks_params:
  #     loader:
  #       callback: CheckpointCallback
  #
  #     raw_processor:
  #       callback: RawMaskPostprocessingCallback
  #       output_key: semantic_mask
  #
  #     image_saver:
  #       callback: OriginalImageSaverCallback
  #       output_dir: infer
  #     saver_semantic:
  #       callback: OverlayMaskImageSaverCallback
  #       output_dir: infer
  #       filename_suffix: _02_semantic_mask
  #       output_key: semantic_mask
