model_params:
  model: ResnetUnet
  num_classes: 1
  arch: resnet18
  pretrained: True

args:
  expdir: "src"
  logdir: &logdir "./logs/binary_segmentation"
  # baselogdir: "./logs/binary_segmentation_base"

stages:

  state_params:
    main_metric: &main_metric iou_hard
    minimize_metric: False

  data_params:
    num_workers: 4
    batch_size: 64
    per_gpu_scaling: True
    in_csv_train: "./data/dataset_train.csv"
    in_csv_valid: "./data/dataset_valid.csv"
    datapath: "./data/dataset"

  criterion_params:
    _key_value: True

    bce:
      criterion: BCEWithLogitsLoss   # FocalLossBinary/BCEWithLogitsLoss
    dice:
      criterion: DiceLoss
    iou:
      criterion: IoULoss

  # train head
  stage1:

    state_params:
      num_epochs: 20

    optimizer_params:
      optimizer: Adam
      lr: 0.001
      weight_decay: 0.0001

    scheduler_params:
      scheduler: MultiStepLR
      milestones: [10]
      gamma: 0.3

    callbacks_params: &callbacks
      loss_bce:
        callback: CriterionCallback
        input_key: mask
        output_key: logits
        prefix: loss_bce
        criterion_key: bce
        multiplier: 1.0
      loss_dice:
        callback: CriterionCallback
        input_key: mask
        output_key: logits
        prefix: loss_dice
        criterion_key: dice
        multiplier: 1.0
      loss_iou:
        callback: CriterionCallback
        input_key: mask
        output_key: logits
        prefix: loss_iou
        criterion_key: iou
        multiplier: 1.0

      loss_aggregator:
        callback: CriterionAggregatorCallback
        prefix: &aggregated_loss loss
        loss_aggregate_fn: "mean" # or "sum"
        multiplier: 1.0 # scale factor for the aggregated loss

      iou_soft:
        callback: IouCallback
        input_key: mask
        output_key: logits
        prefix: iou_soft
      iou_hard:
        callback: IouCallback
        input_key: mask
        output_key: logits
        prefix: iou_hard
        threshold: 0.5

      optimizer:
        callback: OptimizerCallback
        loss_key: *aggregated_loss
      scheduler:
        callback: SchedulerCallback
        reduce_metric: *main_metric
      saver:
        callback: CheckpointCallback

  # tune whole network
  stage2:

    state_params:
      num_epochs: 10

    optimizer_params:
      optimizer: SGD
      lr: 0.0001

    scheduler_params:
      scheduler: MultiStepLR
      milestones: [10]
      gamma: 0.3

    callbacks_params: *callbacks

  infer:

    data_params:
      num_workers: 4
      batch_size: 64
      per_gpu_scaling: True
      in_csv: null
      in_csv_train: null
      in_csv_valid: "./data/dataset_valid.csv"
      in_csv_infer: "./data/dataset_train.csv"
      datapath: "./data/dataset"

    callbacks_params:
      loader:
        callback: CheckpointCallback

      raw_processor:
        callback: RawMaskPostprocessingCallback

      image_saver:
        callback: OriginalImageSaverCallback
        output_dir: infer
      saver_mask:
        callback: OverlayMaskImageSaverCallback
        output_dir: infer
        filename_suffix: _01_raw_mask
        output_key: mask
